import { BusinessTemplate } from '../../types/template';

// ─────────────────────────────────────────────────────────────────────────────
// 1. RESTAURANT & DINING CAFE TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const RESTAURANT_TEMPLATE: BusinessTemplate = {
  templateId: 'RESTAURANT',
  name: 'Restaurant & Dining Cafe',
  description: 'Tailored for dine-in seating, takeaway parcel, kitchen KDS display, recipe ingredient stock deduction, and table bill management.',
  industryCategory: 'Hospitality & Food',
  icon: 'Utensils',
  themeColor: '#C5A059',
  modules: {
    enableServicePoints: true,
    enableFulfillmentStations: true,
    enableBarcodeScanning: false,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: false,
    enableProductVariants: false,
    enableProductBOM: true,
    enableCustomerCreditLedger: false,
    enableLoyaltyProgram: true,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Billing POS', path: '/billing', icon: 'ReceiptText', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Kitchen Orders', path: '/orders', icon: 'ChefHat', rolesAllowed: ['ADMIN', 'MANAGER', 'STAFF'] },
    { name: 'Dining Tables', path: '/tables', icon: 'GripHorizontal', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Dishes & Menu', path: '/menu', icon: 'BookOpen', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Ingredients & Stock', path: '/inventory', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Diners & Loyalty', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Promotions', path: '/promotions', icon: 'Tag', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Starters & Appetizers', description: 'Finger foods, soups and quick bites' },
    { name: 'Main Course', description: 'Curries, biryanis, breads and platters' },
    { name: 'Beverages & Mocktails', description: 'Fresh juices, shakes and drinks' },
    { name: 'Desserts', description: 'Sweets, cakes and ice creams' },
    { name: 'Breads & Accompaniments', description: 'Rotis, naans and salads' },
  ],
  productFields: {
    inputMode: 'TOUCH_GRID',
    visibleFields: ['name', 'categoryId', 'price', 'gst', 'hsnCode', 'kitchenSection', 'dietary', 'isAvailable', 'imageUrl'],
    requiredFields: ['name', 'categoryId', 'price'],
    customAttributes: [
      {
        key: 'dietary',
        label: 'Food Type (Dietary)',
        type: 'SELECT',
        options: ['VEG', 'NON_VEG', 'EGG', 'CHICKEN', 'VEGAN', 'HALAL'],
        default: 'VEG',
        isRequired: true,
        showInGrid: true,
      },
      {
        key: 'kitchenSection',
        label: 'Kitchen Station',
        type: 'SELECT',
        options: ['Main Kitchen', 'Tandoor Section', 'Beverage Bar', 'Dessert Counter'],
        default: 'Main Kitchen',
        showInGrid: true,
      },
      {
        key: 'prepTimeMinutes',
        label: 'Preparation Time (Mins)',
        type: 'NUMBER',
        default: 15,
        showInGrid: true,
      },
      {
        key: 'spiceLevel',
        label: 'Spice Level',
        type: 'SELECT',
        options: ['Mild', 'Medium', 'Spicy', 'Extra Hot'],
        default: 'Medium',
      },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'address', 'birthday', 'anniversary', 'loyaltyPoints'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: false,
  },
  invoiceLayout: {
    defaultFormat: '80MM_THERMAL',
    headerTitle: 'Royal Dine Restaurant',
    tagline: 'Authentic Multi-Cuisine & Family Dining',
    taxLicenseLabel: 'FSSAI Lic No',
    visibleReceiptFields: ['tableNumber', 'orderType', 'kitchenSection', 'itemNotes', 'cgstSgst', 'upiQr'],
    termsText: 'Goods once sold will not be taken back. Subject to local jurisdiction.',
    thankYouNote: 'Thank you for dining with us! Visit again soon 😊',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Revenue", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'todayOrders', title: "Today's Orders", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'kitchenQueue', title: 'Kitchen Queue', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'occupiedTables', title: 'Occupied Tables', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: '14-Day Sales Trend', type: 'BAR_CHART', gridSpan: 4 },
    { id: 'recentOrders', title: 'Day-Wise Dine-In Orders', type: 'TABLE', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'DINE_IN', name: 'Dine-In Table Order', requiresServicePoint: true, defaultPaymentMethod: 'CASH' },
    { code: 'TAKEAWAY', name: 'Takeaway / Parcel Counter', defaultPaymentMethod: 'UPI' },
    { code: 'DELIVERY', name: 'Home Delivery Order', requiresCustomer: true, defaultPaymentMethod: 'CASH' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'All Billing & Customer Details', defaultColumns: ['orderNumber', 'createdAt', 'customerName', 'subtotal', 'tax', 'total'] },
    { id: 'DAILY_SALES', category: 'Sales & Revenue', name: 'Daily Sales Report', defaultColumns: ['date', 'orderCount', 'totalRevenue'] },
    { id: 'ITEM_WISE_SALES', category: 'Product & Inventory', name: 'Item Wise Dish Sales', defaultColumns: ['itemName', 'category', 'qtySold', 'totalAmount'] },
    { id: 'KITCHEN_REPORT', category: 'Operations', name: 'Kitchen Section Performance', defaultColumns: ['section', 'ordersPrepared', 'avgPrepTime'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'GST Tax Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst', 'totalTax'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 5.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '2106',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Food & Beverage GST 5%', rate: 5.0, hsnPrefix: '2106' },
      { label: 'AC Luxury Services GST 18%', rate: 18.0, hsnPrefix: '9963' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'PENDING',
    allowSplitPayments: true,
    allowCreditSale: false,
    requireCustomerForInvoice: false,
    autoPrintOnCheckout: true,
    defaultEstimatedTimeMinutes: 20,
    orderStatusPipeline: [
      { code: 'PENDING', label: 'Order Placed', color: 'orange', nextAllowedStatuses: ['PREPARING', 'CANCELLED'] },
      { code: 'PREPARING', label: 'Kitchen Preparing', color: 'blue', nextAllowedStatuses: ['READY', 'CANCELLED'] },
      { code: 'READY', label: 'Ready for Service', color: 'green', nextAllowedStatuses: ['SERVED'] },
      { code: 'SERVED', label: 'Served to Table', color: 'purple', nextAllowedStatuses: ['COMPLETED'] },
      { code: 'COMPLETED', label: 'Bill Paid & Settled', color: 'emerald', nextAllowedStatuses: [], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Cancelled Order', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 5.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'INV/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: '80MM',
    activeTheme: 'DARK_GOLD',
  },
  terms: {
    itemNoun: 'Dish',
    categoryNoun: 'Food Category',
    orderNoun: 'Table Order',
    invoiceTitle: 'Restaurant Receipt',
    customerNoun: 'Diner',
    servicePointNoun: 'Dining Table',
    fulfillmentNoun: 'Kitchen Station',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 2. RETAIL & GENERAL MERCHANDISE TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const RETAIL_TEMPLATE: BusinessTemplate = {
  templateId: 'RETAIL',
  name: 'Retail Store & General Merchandise',
  description: 'Optimized for high-speed barcode checkout, SKU stock, returns, customer credit ledger, and inventory.',
  industryCategory: 'Retail & FMCG',
  icon: 'Store',
  themeColor: '#3B82F6',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: false,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: false,
    enableProductVariants: true,
    enableProductBOM: false,
    enableCustomerCreditLedger: true,
    enableLoyaltyProgram: true,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Sales POS', path: '/billing', icon: 'ShoppingCart', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Product Catalog', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Inventory Stock', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Customers & Credit', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Discounts & Offers', path: '/promotions', icon: 'Tag', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Home & Kitchen', description: 'Utensils, storage and appliances' },
    { name: 'Packaged Foods', description: 'Snacks, biscuits and beverages' },
    { name: 'Personal Care', description: 'Soaps, shampoos and skincare' },
    { name: 'Stationery & Office', description: 'Pens, notebooks and books' },
    { name: 'General Goods', description: 'Miscellaneous household products' },
  ],
  productFields: {
    inputMode: 'BARCODE_SCANNER',
    visibleFields: ['sku', 'barcode', 'name', 'categoryId', 'brand', 'costPrice', 'sellingPrice', 'mrp', 'gst', 'hsnCode', 'currentStock'],
    requiredFields: ['sku', 'name', 'sellingPrice'],
    customAttributes: [
      { key: 'brand', label: 'Brand Name', type: 'TEXT', showInGrid: true },
      { key: 'color', label: 'Color Variant', type: 'TEXT', showInGrid: true },
      { key: 'warrantyMonths', label: 'Warranty (Months)', type: 'NUMBER', default: 12, showInGrid: true },
      { key: 'unitOfMeasure', label: 'Unit of Measure', type: 'SELECT', options: ['PCS', 'KG', 'GRAM', 'LITER', 'PACKET', 'BOX'], default: 'PCS', showInGrid: true },
      { key: 'rackLocation', label: 'Aisle / Rack Location', type: 'TEXT' },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'email', 'address', 'gstNumber', 'loyaltyPoints', 'creditLimit'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: true,
  },
  invoiceLayout: {
    defaultFormat: '80MM_THERMAL',
    headerTitle: 'Retail Mart & General Store',
    tagline: 'Your Daily Shopping Destination',
    taxLicenseLabel: 'Trade License No',
    visibleReceiptFields: ['barcode', 'sku', 'qty', 'mrp', 'discount', 'savingsSummary', 'taxSummary', 'upiQr'],
    termsText: 'Items once sold can be exchanged within 7 days with original cash memo.',
    thankYouNote: 'Thank you for shopping with us! Have a wonderful day.',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Total Sales", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'itemsSold', title: 'Items Sold Today', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'totalCustomers', title: 'Walk-In Customers', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'lowStockAlerts', title: 'Low Stock Alerts', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Sales Trend', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'RETAIL_SALE', name: 'Sales POS (Cash / Card Sale)', defaultPaymentMethod: 'CASH' },
    { code: 'PURCHASE_ENTRY', name: 'Purchase (Supplier Goods Inward)', defaultPaymentMethod: 'BANK_TRANSFER' },
    { code: 'RETURN_EXCHANGE', name: 'Return / Exchange Credit Memo', defaultPaymentMethod: 'CASH' },
    { code: 'CREDIT_SALE', name: 'Customer Credit Sale (Pay Later)', requiresCustomer: true, requiresCreditApproval: true },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Retail Sales Register', defaultColumns: ['orderNumber', 'createdAt', 'customerName', 'total'] },
    { id: 'TOP_SELLING_ITEMS', category: 'Product & Inventory', name: 'Top Selling Products', defaultColumns: ['barcode', 'itemName', 'qtySold', 'totalAmount'] },
    { id: 'STOCK_VALUATION', category: 'Product & Inventory', name: 'Inventory Valuation Report', defaultColumns: ['itemName', 'currentStock', 'costPrice', 'totalValuation'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'GST B2C Tax Report', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '8471',
    taxExemptAllowed: true,
    taxSlabs: [
      { label: 'Standard Goods GST 18%', rate: 18.0 },
      { label: 'Essential FMCG GST 5%', rate: 5.0 },
      { label: 'Standard Packaged GST 12%', rate: 12.0 },
      { label: 'Tax Exempt / 0%', rate: 0.0 },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: true,
    requireCustomerForInvoice: false,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'COMPLETED', label: 'Sale Completed', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Refunded / Cancelled', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'RTL/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: '80MM',
    activeTheme: 'DARK_SLATE',
  },
  terms: {
    itemNoun: 'Product',
    categoryNoun: 'Department',
    orderNoun: 'Sales Counter Bill',
    invoiceTitle: 'Retail Cash Memo',
    customerNoun: 'Shopper',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 3. SUPERMARKET & GROCERY HYPERMARKET TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const SUPERMARKET_TEMPLATE: BusinessTemplate = {
  templateId: 'SUPERMARKET',
  name: 'Supermarket & Grocery Hypermarket',
  description: 'Engineered for high-volume rapid barcode scanning, weighing scale integration, FMCG batch control, and loyalty reward tiers.',
  industryCategory: 'Retail & FMCG',
  icon: 'ShoppingCart',
  themeColor: '#10B981',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: false,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: true,
    enableSerialIMEI: false,
    enableProductVariants: true,
    enableProductBOM: false,
    enableCustomerCreditLedger: false,
    enableLoyaltyProgram: true,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Fast Checkout POS', path: '/billing', icon: 'ShoppingCart', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Grocery Inventory', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Stock & Batches', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Club Members', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Discounts & Combos', path: '/promotions', icon: 'Tag', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Fruits & Fresh Vegetables', description: 'Daily fresh farm produce' },
    { name: 'Dairy, Bread & Eggs', description: 'Milk, butter, cheese and bakery items' },
    { name: 'Rice, Atta & Dals', description: 'Grains, flour and pulses' },
    { name: 'Snacks & Packaged Foods', description: 'Biscuits, noodles and ready to eat' },
    { name: 'Beverages & Cold Drinks', description: 'Soft drinks, tea and coffee' },
    { name: 'Cleaning & Household', description: 'Detergents, soaps and sprays' },
  ],
  productFields: {
    inputMode: 'BARCODE_SCANNER',
    visibleFields: ['barcode', 'sku', 'name', 'categoryId', 'costPrice', 'sellingPrice', 'mrp', 'gst', 'currentStock'],
    requiredFields: ['barcode', 'name', 'sellingPrice'],
    customAttributes: [
      { key: 'brand', label: 'Brand', type: 'TEXT', showInGrid: true },
      { key: 'weightType', label: 'Unit / Weight', type: 'SELECT', options: ['PCS', 'KG', 'GRAM', 'PACKET'], default: 'PCS', showInGrid: true },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'loyaltyPoints', 'email'],
    requiredFields: ['mobile'],
    allowCreditBilling: false,
  },
  invoiceLayout: {
    defaultFormat: '80MM_THERMAL',
    headerTitle: 'SuperMart Hypermarket',
    tagline: 'Freshness, Quality & Savings Everyday',
    taxLicenseLabel: 'GSTIN / FSSAI Lic',
    visibleReceiptFields: ['barcode', 'qty', 'mrp', 'discount', 'savingsSummary', 'loyaltyPointsEarned', 'taxSummary', 'upiQr'],
    termsText: 'No cash returns. Exchanges within 3 days for sealed FMCG goods.',
    thankYouNote: 'Thank you for choosing SuperMart! You saved money today.',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Turnover", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'itemsSold', title: 'Units Scanned', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'avgTicket', title: 'Average Cart Size', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'lowStockAlerts', title: 'Reorder Alerts', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Hourly Sales Pattern', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'SUPERMARKET_COUNTER', name: 'Express Lane Checkout', defaultPaymentMethod: 'UPI' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Cash Register Transactions', defaultColumns: ['orderNumber', 'createdAt', 'total'] },
    { id: 'TOP_SELLING_ITEMS', category: 'Product & Inventory', name: 'Top Fast-Moving FMCG', defaultColumns: ['barcode', 'itemName', 'qtySold', 'totalAmount'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'GSTR-1 B2C Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 5.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '0401',
    taxExemptAllowed: true,
    taxSlabs: [
      { label: 'Exempted Food Items 0%', rate: 0.0 },
      { label: 'Essential Groceries 5%', rate: 5.0 },
      { label: 'Packaged Goods 12%', rate: 12.0 },
      { label: 'Household & Cleaning 18%', rate: 18.0 },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: false,
    requireCustomerForInvoice: false,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'COMPLETED', label: 'Billed', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Voided Bill', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 5.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'SM/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: '80MM',
    activeTheme: 'EMERALD',
  },
  terms: {
    itemNoun: 'Grocery Item',
    categoryNoun: 'Aisle Category',
    orderNoun: 'Express Bill',
    invoiceTitle: 'Supermarket Cash Bill',
    customerNoun: 'Club Member',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 4. MEDICAL STORE & PHARMACY TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const MEDICAL_TEMPLATE: BusinessTemplate = {
  templateId: 'MEDICAL',
  name: 'Medical Store & Pharmacy',
  description: 'Designed for pharmacies with Batch No tracking, Expiry Date alerts, Schedule H/H1 regulatory controls, and Doctor/Patient details.',
  industryCategory: 'Healthcare',
  icon: 'Pill',
  themeColor: '#10B981',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: false,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: true,
    enableSerialIMEI: false,
    enableProductVariants: false,
    enableProductBOM: false,
    enableCustomerCreditLedger: true,
    enableLoyaltyProgram: false,
    enablePromotionsEngine: false,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: false,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Pharmacy POS', path: '/billing', icon: 'ReceiptText', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Medicine Catalog', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Batch & Expiry Stock', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Patients & Doctors', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Audit Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Tablets & Capsules', description: 'Oral solid dosage formulations' },
    { name: 'Syrups & Suspensions', description: 'Liquid oral medications' },
    { name: 'Injections & Vials', description: 'Parenteral medicines' },
    { name: 'Ointments & Creams', description: 'Topical formulations' },
    { name: 'Surgical & Healthcare Devices', description: 'Bandages, thermometers and BP monitors' },
    { name: 'Nutritional Supplements & OTC', description: 'Vitamins, tonics and protein powders' },
  ],
  productFields: {
    inputMode: 'BATCH_PICKER',
    visibleFields: ['sku', 'barcode', 'name', 'composition', 'scheduleH', 'categoryId', 'costPrice', 'sellingPrice', 'mrp', 'gst', 'hsnCode'],
    requiredFields: ['name', 'sellingPrice'],
    customAttributes: [
      { key: 'batchNumber', label: 'Batch No', type: 'TEXT', placeholder: 'e.g. BCH-2026-X', isRequired: true, showInGrid: true },
      { key: 'expiryDate', label: 'Expiry Date', type: 'DATE', isRequired: true, showInGrid: true },
      { key: 'composition', label: 'Salt / Composition', type: 'TEXT', placeholder: 'e.g. Paracetamol 500mg', showInGrid: true },
      { key: 'mfgCompany', label: 'Manufacturer', type: 'TEXT', placeholder: 'e.g. Cipla / Sun Pharma', showInGrid: true },
      { key: 'scheduleH', label: 'Schedule H / H1 Drug (Rx Mandatory)', type: 'BOOLEAN', default: false, showInGrid: true },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'patientAge', 'doctorName', 'doctorRegNo', 'address'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: true,
  },
  invoiceLayout: {
    defaultFormat: 'PHARMACY_INVOICE',
    headerTitle: 'LifeCare Pharmacy & Chemist',
    tagline: 'Your Trusted Health & Wellness Partner',
    taxLicenseLabel: 'Drug License No (DL-20B/21B)',
    visibleReceiptFields: ['doctorName', 'patientName', 'batchNumber', 'expiryDate', 'mfgName', 'scheduleHWarning', 'hsnSummary', 'upiQr'],
    termsText: 'Schedule H & H1 drugs sold against valid registered medical practitioner prescription only.',
    thankYouNote: 'Wishing you speedy recovery and good health!',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Pharmacy Sales", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'prescriptionsBilled', title: 'Prescription Count', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'nearExpiryCount', title: 'Expiry Alert (Near Expiry)', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'lowStockAlerts', title: 'Stock Alert (Reorder)', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Pharmacy Sales Trend', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'PRESCRIPTION_BILL', name: 'Prescription Sale (Rx Required)', requiresDoctor: true, requiresCustomer: true, defaultPaymentMethod: 'CASH' },
    { code: 'OTC_BILL', name: 'Over The Counter (OTC)', defaultPaymentMethod: 'UPI' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Pharmacy Sales Register', defaultColumns: ['orderNumber', 'patientName', 'doctorName', 'total'] },
    { id: 'EXPIRY_SCHEDULE_REPORT', category: 'Compliance & Audit', name: 'Medicine Expiry Schedule (30/60/90 Days)', defaultColumns: ['medicineName', 'batchNumber', 'expiryDate', 'stockRemaining'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'Pharmacy Tax Report', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 12.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '3004',
    taxExemptAllowed: true,
    taxSlabs: [
      { label: 'Life Saving Medicines 5%', rate: 5.0, hsnPrefix: '3004' },
      { label: 'Standard Formulations 12%', rate: 12.0, hsnPrefix: '3004' },
      { label: 'Surgical & Cosmetics 18%', rate: 18.0, hsnPrefix: '3304' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'PENDING',
    allowSplitPayments: true,
    allowCreditSale: true,
    requireCustomerForInvoice: true,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'PENDING', label: 'Prescription Received', color: 'orange', nextAllowedStatuses: ['APPROVED', 'CANCELLED'] },
      { code: 'APPROVED', label: 'Pharmacist Approved / Verified', color: 'blue', nextAllowedStatuses: ['COMPLETED', 'CANCELLED'], rolesAllowed: ['ADMIN', 'MANAGER', 'STAFF'] },
      { code: 'COMPLETED', label: 'Dispensed & Billed', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Prescription Rejected', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 12.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'MED/',
    orderPrefix: 'RX-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: '80MM',
    activeTheme: 'EMERALD',
  },
  terms: {
    itemNoun: 'Medicine',
    categoryNoun: 'Drug Category',
    orderNoun: 'Prescription Invoice',
    invoiceTitle: 'Pharmacy Cash Invoice',
    customerNoun: 'Patient',
    fulfillmentNoun: 'Dispensing Counter',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 5. BAKERY & CONFECTIONERY TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const BAKERY_TEMPLATE: BusinessTemplate = {
  templateId: 'BAKERY',
  name: 'Bakery & Confectionery Shop',
  description: 'Features fresh shelf-life batch control, custom cake pre-orders with advance payments, and ingredient recipe stock deduction.',
  industryCategory: 'Hospitality & Food',
  icon: 'Cake',
  themeColor: '#EC4899',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: true,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: true,
    enableSerialIMEI: false,
    enableProductVariants: false,
    enableProductBOM: true,
    enableCustomerCreditLedger: false,
    enableLoyaltyProgram: true,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Bakery POS', path: '/billing', icon: 'ShoppingBag', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Cake Pre-Orders', path: '/orders', icon: 'Calendar', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Bakery Items', path: '/menu', icon: 'BookOpen', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Ingredients & BOM', path: '/inventory', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Fresh Breads & Buns', description: 'White bread, whole wheat and croissants' },
    { name: 'Custom & Designer Cakes', description: 'Birthday, wedding and anniversary cakes' },
    { name: 'Pastries & Desserts', description: 'Tarts, donuts, muffins and cheesecakes' },
    { name: 'Savories & Puffs', description: 'Veg puffs, rolls and quiches' },
    { name: 'Cookies & Biscuits', description: 'Artisanal butter and almond cookies' },
  ],
  productFields: {
    inputMode: 'TOUCH_GRID',
    visibleFields: ['name', 'categoryId', 'price', 'gst', 'hsnCode', 'isAvailable', 'shelfLifeHours'],
    requiredFields: ['name', 'price'],
    customAttributes: [
      { key: 'shelfLifeHours', label: 'Shelf Life (Hours)', type: 'NUMBER', default: 24, showInGrid: true },
      { key: 'eggless', label: '100% Eggless', type: 'BOOLEAN', default: true, showInGrid: true },
      { key: 'flavor', label: 'Cake Flavor', type: 'SELECT', options: ['Chocolate', 'Vanilla', 'Red Velvet', 'Black Forest', 'Butterscotch'] },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'address', 'birthday', 'anniversary', 'loyaltyPoints'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: false,
  },
  invoiceLayout: {
    defaultFormat: '80MM_THERMAL',
    headerTitle: 'Royal Oven Bakery & Cafe',
    tagline: 'Fresh Breads, Custom Cakes & Confections',
    taxLicenseLabel: 'FSSAI Lic No',
    visibleReceiptFields: ['deliveryDate', 'cakeMessage', 'advancePaid', 'balanceDue', 'storageInstructions', 'upiQr'],
    termsText: 'Best consumed fresh within stated hours. Keep refrigerated.',
    thankYouNote: 'Thank you for sweetening your celebrations with Royal Oven!',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Bakery Revenue", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'preOrdersPending', title: 'Custom Cake Orders Pending', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Sales Trend', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'COUNTER_SALE', name: 'Bakery Counter Sale', defaultPaymentMethod: 'CASH' },
    { code: 'CAKE_PREORDER', name: 'Custom Cake Pre-Order (Advance)', requiresCustomer: true, defaultPaymentMethod: 'UPI' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Bakery Sales Register', defaultColumns: ['orderNumber', 'customerName', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'Bakery Tax Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 5.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '1905',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Bakery Breads & Pastries 5%', rate: 5.0, hsnPrefix: '1905' },
      { label: 'Chocolates & Confectionery 18%', rate: 18.0, hsnPrefix: '1806' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: false,
    requireCustomerForInvoice: false,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'PENDING', label: 'Bake Order Booked', color: 'orange', nextAllowedStatuses: ['PREPARING'] },
      { code: 'PREPARING', label: 'In Baking / Frosting', color: 'blue', nextAllowedStatuses: ['READY'] },
      { code: 'READY', label: 'Ready for Pickup', color: 'green', nextAllowedStatuses: ['COMPLETED'] },
      { code: 'COMPLETED', label: 'Handed Over & Paid', color: 'emerald', nextAllowedStatuses: [], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Cancelled', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 5.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'BAK/',
    orderPrefix: 'CAKE-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: '80MM',
    activeTheme: 'DARK_GOLD',
  },
  terms: {
    itemNoun: 'Bakery Item',
    categoryNoun: 'Confectionery Section',
    orderNoun: 'Cake / Counter Bill',
    invoiceTitle: 'Bakery Receipt',
    customerNoun: 'Customer',
    fulfillmentNoun: 'Bakehouse Kitchen',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 6. ELECTRONICS & MOBILE STORE TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const ELECTRONICS_TEMPLATE: BusinessTemplate = {
  templateId: 'ELECTRONICS',
  name: 'Electronics & Mobile Store',
  description: 'Specialized for tracking unique Serial Numbers, IMEI codes, brand warranty periods, and GST input credit tax invoices.',
  industryCategory: 'Retail & FMCG',
  icon: 'Smartphone',
  themeColor: '#0EA5E9',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: false,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: true,
    enableProductVariants: true,
    enableProductBOM: false,
    enableCustomerCreditLedger: true,
    enableLoyaltyProgram: false,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Sales POS', path: '/billing', icon: 'ShoppingCart', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Devices & Models', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Serial & Stock', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Customers & Warranty', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Smartphones & Tablets', description: 'Android, iOS and tablets' },
    { name: 'Laptops & Computers', description: 'Gaming, ultrabooks and desktops' },
    { name: 'Audio & Wearables', description: 'Earbuds, headphones and smartwatches' },
    { name: 'Home Appliances', description: 'Smart TVs, refrigerators and ACs' },
    { name: 'Accessories & Cables', description: 'Chargers, cases, power banks and converters' },
  ],
  productFields: {
    inputMode: 'BARCODE_SCANNER',
    visibleFields: ['sku', 'barcode', 'name', 'brand', 'modelNo', 'costPrice', 'sellingPrice', 'gst', 'hsnCode'],
    requiredFields: ['name', 'sellingPrice'],
    customAttributes: [
      { key: 'ram', label: 'RAM', type: 'SELECT', options: ['4GB', '6GB', '8GB', '12GB', '16GB', '32GB', '64GB'], default: '8GB', showInGrid: true },
      { key: 'storage', label: 'Storage Capacity', type: 'SELECT', options: ['64GB', '128GB', '256GB', '512GB', '1TB', '2TB'], default: '256GB', showInGrid: true },
      { key: 'processor', label: 'Processor / Chipset', type: 'TEXT', placeholder: 'e.g. Apple M3 / Snapdragon 8 Gen 3', showInGrid: true },
      { key: 'serialNumber', label: 'Serial / IMEI No', type: 'TEXT', isRequired: true, showInGrid: true },
      { key: 'warrantyMonths', label: 'Brand Warranty (Months)', type: 'NUMBER', default: 12, showInGrid: true },
      { key: 'color', label: 'Color / Variant', type: 'TEXT' },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'email', 'address', 'gstNumber'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: true,
  },
  invoiceLayout: {
    defaultFormat: 'A4_TAX_INVOICE',
    headerTitle: 'NextGen Electronics & Mobiles',
    tagline: 'Genuine Gadgets, Official Brand Warranty',
    taxLicenseLabel: 'GSTIN / Trade Lic',
    visibleReceiptFields: ['serialNumber', 'warrantyMonths', 'modelNo', 'hsnSummaryTable', 'amountInWords', 'signatureLine'],
    termsText: 'Goods once sold are covered under authorized brand manufacturer warranty.',
    thankYouNote: 'Thank you for choosing NextGen Electronics!',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Gadget Sales", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'itemsSold', title: 'Devices Sold', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Monthly Revenue', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'ELECTRONICS_TAX_INVOICE', name: 'Tax Invoice with Warranty', requiresCustomer: true, defaultPaymentMethod: 'CARD' },
    { code: 'ACCESSORY_CASH_MEMO', name: 'Quick Accessory Sale', defaultPaymentMethod: 'UPI' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Electronics Tax Register', defaultColumns: ['orderNumber', 'customerName', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'GSTR-1 Tax Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '8517',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Smartphones & Peripherals 18%', rate: 18.0, hsnPrefix: '8517' },
      { label: 'Large Appliances 28%', rate: 28.0, hsnPrefix: '8415' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: true,
    requireCustomerForInvoice: true,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'COMPLETED', label: 'Device Sold & Serial Logged', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Returned / Replaced', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'ELE/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: 'A4',
    activeTheme: 'DARK_SLATE',
  },
  terms: {
    itemNoun: 'Device / Gadget',
    categoryNoun: 'Category',
    orderNoun: 'Tax Invoice',
    invoiceTitle: 'Electronics Tax Invoice',
    customerNoun: 'Buyer',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 7. HARDWARE & BUILDING MATERIALS TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const HARDWARE_TEMPLATE: BusinessTemplate = {
  templateId: 'HARDWARE',
  name: 'Hardware & Sanitary Store',
  description: 'Built for managing loose weight items, electricals, plumbing fittings, contractor ledgers, and bulk discount pricing.',
  industryCategory: 'Industrial & Hardware',
  icon: 'Wrench',
  themeColor: '#F59E0B',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: false,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: false,
    enableProductVariants: true,
    enableProductBOM: false,
    enableCustomerCreditLedger: true,
    enableLoyaltyProgram: false,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Hardware POS', path: '/billing', icon: 'ReceiptText', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Items & Tools', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Stock & Warehouse', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Contractor Ledgers', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Pipes & Sanitary Fittings', description: 'PVC, CPVC pipes and taps' },
    { name: 'Electrical & Lighting', description: 'Wires, switches, MCBs and LED bulbs' },
    { name: 'Paints & Chemicals', description: 'Emulsions, primers and sealants' },
    { name: 'Hand & Power Tools', description: 'Drills, saws, hammers and wrenches' },
    { name: 'Fasteners & Screws', description: 'Nuts, bolts, washers and anchors' },
  ],
  productFields: {
    inputMode: 'SKU_LOOKUP',
    visibleFields: ['sku', 'name', 'categoryId', 'unitOfMeasure', 'costPrice', 'sellingPrice', 'gst', 'hsnCode', 'currentStock'],
    requiredFields: ['name', 'sellingPrice'],
    customAttributes: [
      { key: 'unitOfMeasure', label: 'Unit (Kg/Mtr/Pcs/Box)', type: 'SELECT', options: ['PCS', 'KG', 'METER', 'FEET', 'LITER', 'BOX', 'BUNDLE'], default: 'PCS', showInGrid: true },
      { key: 'sizeSpec', label: 'Dimension / Size (e.g. 1/2 inch, 25mm)', type: 'TEXT', showInGrid: true },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'address', 'gstNumber', 'creditLimit', 'creditDays'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: true,
  },
  invoiceLayout: {
    defaultFormat: 'A4_TAX_INVOICE',
    headerTitle: 'Apex Hardware & Building Supplies',
    tagline: 'Quality Tools, Paints, Electricals & Plumbing',
    taxLicenseLabel: 'GSTIN / Trade Lic',
    visibleReceiptFields: ['hsnSummaryTable', 'contractorName', 'amountInWords', 'signatureLine'],
    termsText: 'Pipes and cut wires cannot be returned. Payment due within credit terms.',
    thankYouNote: 'Thank you for your business!',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Hardware Billing", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Sales Trend', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'HARDWARE_TAX_INVOICE', name: 'Contractor Tax Invoice', requiresCustomer: true, defaultPaymentMethod: 'CASH' },
    { code: 'RETAIL_CASH_MEMO', name: 'Walk-in Cash Memo', defaultPaymentMethod: 'UPI' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Hardware Sales Register', defaultColumns: ['orderNumber', 'customerName', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'GST Tax Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '7318',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Standard Hardware 18%', rate: 18.0 },
      { label: 'Paints & Adhesives 28%', rate: 28.0 },
      { label: 'Iron & Steel Raw 18%', rate: 18.0 },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: true,
    requireCustomerForInvoice: false,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'COMPLETED', label: 'Billed & Dispatched', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Cancelled / Returned', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'HDW/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: 'A4',
    activeTheme: 'DARK_GOLD',
  },
  terms: {
    itemNoun: 'Hardware Item',
    categoryNoun: 'Category',
    orderNoun: 'Hardware Bill',
    invoiceTitle: 'Hardware Tax Invoice',
    customerNoun: 'Contractor / Customer',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 8. GARMENTS & APPAREL BOUTIQUE TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const GARMENTS_TEMPLATE: BusinessTemplate = {
  templateId: 'GARMENTS',
  name: 'Garments & Fashion Boutique',
  description: 'Designed for apparel stores with Size / Color matrix, barcode tag scanning, seasonal trial room tags, and exchange policies.',
  industryCategory: 'Apparel & Luxury',
  icon: 'Shirt',
  themeColor: '#8B5CF6',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: false,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: false,
    enableProductVariants: true,
    enableProductBOM: false,
    enableCustomerCreditLedger: false,
    enableLoyaltyProgram: true,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Boutique POS', path: '/billing', icon: 'ShoppingCart', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Fashion Apparel', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Inventory & Sizes', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'VIP Shoppers', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Discounts & Deals', path: '/promotions', icon: 'Tag', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: "Men's Formal & Casuals", description: 'Shirts, trousers, jeans and t-shirts' },
    { name: "Women's Ethnic & Western", description: 'Kurtis, sarees, tops and dresses' },
    { name: "Kids & Infant Wear", description: 'Boys, girls and infant sets' },
    { name: "Winterwear & Jackets", description: 'Sweaters, blazers and hoodies' },
    { name: "Fashion Accessories", description: 'Belts, ties, scarves and wallets' },
  ],
  productFields: {
    inputMode: 'BARCODE_SCANNER',
    visibleFields: ['barcode', 'sku', 'name', 'brand', 'costPrice', 'sellingPrice', 'mrp', 'gst', 'hsnCode', 'currentStock'],
    requiredFields: ['name', 'sellingPrice'],
    customAttributes: [
      { key: 'size', label: 'Size (S/M/L/XL/XXL/Numeric)', type: 'SELECT', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '30', '32', '34', '36', '38', '40'], default: 'M', showInGrid: true },
      { key: 'color', label: 'Color Variant', type: 'TEXT', showInGrid: true },
      { key: 'fabric', label: 'Fabric / Material (Cotton/Silk/Denim)', type: 'TEXT' },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'birthday', 'anniversary', 'loyaltyPoints'],
    requiredFields: ['mobile'],
    allowCreditBilling: false,
  },
  invoiceLayout: {
    defaultFormat: '80MM_THERMAL',
    headerTitle: 'Vogue Fashion & Apparel',
    tagline: 'Trendy Styles & Designer Collections',
    taxLicenseLabel: 'GSTIN / Trade Lic',
    visibleReceiptFields: ['size', 'color', 'barcode', 'mrp', 'discount', 'savingsSummary', 'upiQr'],
    termsText: 'Garments once sold can be exchanged within 7 days with original tag attached.',
    thankYouNote: 'Thank you for shopping at Vogue Fashion! Style yourself everyday.',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Apparel Sales", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'itemsSold', title: 'Garments Sold', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Weekly Fashion Trend', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'BOUTIQUE_SALE', name: 'Fashion POS Checkout', defaultPaymentMethod: 'CARD' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Garment Sales Register', defaultColumns: ['orderNumber', 'customerName', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'Apparel GST Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 12.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '6203',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Apparel below ₹1000 (GST 5%)', rate: 5.0, hsnPrefix: '6203' },
      { label: 'Apparel above ₹1000 (GST 12%)', rate: 12.0, hsnPrefix: '6203' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: false,
    requireCustomerForInvoice: false,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'COMPLETED', label: 'Purchased', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Exchanged / Returned', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 12.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'VOG/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: '80MM',
    activeTheme: 'DARK_GOLD',
  },
  terms: {
    itemNoun: 'Garment',
    categoryNoun: 'Section',
    orderNoun: 'Apparel Bill',
    invoiceTitle: 'Boutique Cash Memo',
    customerNoun: 'Shopper',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 9. JEWELLERY & GOLD SHOWROOM TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const JEWELLERY_TEMPLATE: BusinessTemplate = {
  templateId: 'JEWELLERY',
  name: 'Jewellery & Gold Showroom',
  description: 'Precision hallmarked jewellery billing calculating Gold/Silver live rates, Gross/Net Weight, Making Charges, and 3% GST.',
  industryCategory: 'Apparel & Luxury',
  icon: 'Gem',
  themeColor: '#EAB308',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: false,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: false,
    enableProductVariants: false,
    enableProductBOM: false,
    enableCustomerCreditLedger: false,
    enableLoyaltyProgram: true,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Jewellery POS', path: '/billing', icon: 'ReceiptText', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Ornaments Catalog', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Vault & Stock', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Clients & KYC', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: '22K Gold Ornaments', description: 'Necklaces, bangles, rings and earrings' },
    { name: '18K Diamond Jewellery', description: 'Certified solitaires, pendants and studs' },
    { name: 'Silver Articles & Utensils', description: 'Pooja items, coins and silver anklets' },
    { name: 'Platinum Bands', description: 'Love bands and couple rings' },
    { name: 'Gold Bullion & Coins', description: '24K 999 purity investment coins and bars' },
  ],
  productFields: {
    inputMode: 'TOUCH_GRID',
    visibleFields: ['name', 'categoryId', 'purity', 'grossWeight', 'netWeight', 'makingChargePerGram', 'price', 'gst', 'hsnCode'],
    requiredFields: ['name', 'price'],
    customAttributes: [
      { key: 'purity', label: 'Gold / Metal Purity', type: 'SELECT', options: ['24K (999)', '22K (916 Hallmarked)', '18K (750)', 'Silver 92.5'], default: '22K (916 Hallmarked)', showInGrid: true },
      { key: 'grossWeight', label: 'Gross Weight (Grams)', type: 'NUMBER', isRequired: true, showInGrid: true },
      { key: 'huidCode', label: 'HUID Hallmarking Code', type: 'TEXT', showInGrid: true },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'address', 'gstNumber', 'panCard'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: false,
  },
  invoiceLayout: {
    defaultFormat: 'A4_TAX_INVOICE',
    headerTitle: 'Kalyan Heritage Jewellers',
    tagline: 'Pure 916 Hallmarked Gold & Certified Diamonds',
    taxLicenseLabel: 'BIS Hallmarking Reg / GSTIN',
    visibleReceiptFields: ['purity', 'grossWeight', 'huidCode', 'makingCharges', 'hsnSummaryTable', 'amountInWords', 'signatureLine'],
    termsText: 'Gold purity certified under BIS Hallmark. Buyback subject to daily market rate and assay test.',
    thankYouNote: 'Thank you for making us a part of your auspicious celebrations.',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Gold TurnOver", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Monthly Revenue', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'GOLD_TAX_INVOICE', name: 'Hallmarked Gold Tax Invoice', requiresCustomer: true, defaultPaymentMethod: 'UPI' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Jewellery Tax Register', defaultColumns: ['orderNumber', 'customerName', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'GST 3% Tax Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 3.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '7113',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Gold & Diamond Jewellery GST 3%', rate: 3.0, hsnPrefix: '7113' },
      { label: 'Making Charges GST 5%', rate: 5.0, hsnPrefix: '9988' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: false,
    requireCustomerForInvoice: true,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'COMPLETED', label: 'Sold & Invoiced', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Cancelled', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 3.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'JWL/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: 'A4',
    activeTheme: 'DARK_GOLD',
  },
  terms: {
    itemNoun: 'Jewellery Article',
    categoryNoun: 'Metal Category',
    orderNoun: 'Jewellery Invoice',
    invoiceTitle: 'Tax Invoice (Hallmarked)',
    customerNoun: 'Client',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 10. WHOLESALE & B2B DISTRIBUTOR TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const WHOLESALE_TEMPLATE: BusinessTemplate = {
  templateId: 'WHOLESALE',
  name: 'Wholesale & B2B Distributor',
  description: 'Features B2B Tax Invoices, Master Carton Box Quantities, Customer Credit Limits, E-Way Bill fields, and Tier Pricing.',
  industryCategory: 'Industrial & Hardware',
  icon: 'Factory',
  themeColor: '#A855F7',
  modules: {
    enableServicePoints: false,
    enableFulfillmentStations: true,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: true,
    enableSerialIMEI: false,
    enableProductVariants: false,
    enableProductBOM: false,
    enableCustomerCreditLedger: true,
    enableLoyaltyProgram: false,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'B2B Billing', path: '/billing', icon: 'FileText', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Client Ledgers', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Wholesale Products', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Warehouse Stock', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Discounts & Tiers', path: '/promotions', icon: 'Tag', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Bulk Fast Moving Goods', description: 'Master carton packaged consumer goods' },
    { name: 'Industrial Raw Supplies', description: 'Bulk industrial packing supplies' },
    { name: 'Institutional Supplies', description: 'Commercial cleaning and cafeteria items' },
  ],
  productFields: {
    inputMode: 'SKU_LOOKUP',
    visibleFields: ['sku', 'barcode', 'name', 'categoryId', 'unitOfMeasure', 'boxQuantity', 'wholesalePrice', 'retailPrice', 'gst', 'hsnCode', 'currentStock'],
    requiredFields: ['sku', 'name', 'wholesalePrice'],
    customAttributes: [
      { key: 'boxQuantity', label: 'Master Carton Qty', type: 'NUMBER', default: 24, showInGrid: true },
      { key: 'moq', label: 'Minimum Order Qty (MOQ)', type: 'NUMBER', default: 10, showInGrid: true },
    ],
  },
  customerFields: {
    visibleFields: ['companyName', 'name', 'mobile', 'gstNumber', 'billingAddress', 'shippingAddress', 'creditLimit', 'creditDays'],
    requiredFields: ['companyName', 'mobile', 'gstNumber'],
    allowCreditBilling: true,
  },
  invoiceLayout: {
    defaultFormat: 'B2B_WHOLESALE',
    headerTitle: 'Apex Wholesale & Distribution Corp',
    tagline: 'Authorized National Master Distributor',
    taxLicenseLabel: 'GSTIN / Corporate Reg',
    visibleReceiptFields: ['customerGstin', 'placeOfSupply', 'ewayBillNo', 'poNumber', 'hsnSummaryTable', 'amountInWords', 'signatureLine'],
    termsText: 'Payment due within specified credit period. Interest @18% p.a. levied on overdue bills.',
    thankYouNote: 'Thank you for partnering with Apex Distributors!',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's B2B Billing", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'todayOrders', title: 'Invoices Raised', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'totalCustomers', title: 'Active B2B Clients', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'lowStockAlerts', title: 'Warehouse Reorder Level', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Monthly B2B Sales Trend', type: 'BAR_CHART', gridSpan: 4 },
    { id: 'recentOrders', title: 'B2B Tax Invoices', type: 'TABLE', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'B2B_GST_SALE', name: 'GST Sale (B2B Tax Invoice)', requiresCustomer: true, defaultPaymentMethod: 'BANK_TRANSFER' },
    { code: 'CREDIT_SALE', name: 'Credit Sale (Wholesale Pay Later)', requiresCustomer: true, requiresCreditApproval: true },
    { code: 'PROFORMA_INVOICE', name: 'Proforma Quotation / Estimate', defaultPaymentMethod: 'CASH' },
    { code: 'CASH_BILL', name: 'Counter Cash Memo', defaultPaymentMethod: 'CASH' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'B2B Tax Invoice Register', defaultColumns: ['orderNumber', 'companyName', 'gstin', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'GSTR-1 Outward Tax Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst', 'igst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '8471',
    taxExemptAllowed: true,
    taxSlabs: [
      { label: 'Standard Wholesale Goods 18%', rate: 18.0 },
      { label: 'Reduced Rate 12%', rate: 12.0 },
      { label: 'Essential Bulk 5%', rate: 5.0 },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: true,
    requireCustomerForInvoice: true,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'PENDING', label: 'PO Received', color: 'orange', nextAllowedStatuses: ['PREPARING'] },
      { code: 'PREPARING', label: 'Warehouse Picking', color: 'blue', nextAllowedStatuses: ['COMPLETED'] },
      { code: 'COMPLETED', label: 'Dispatched & Invoiced', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Cancelled Order', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'WHOLE/',
    orderPrefix: 'PO-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: 'A4',
    activeTheme: 'DARK_SLATE',
  },
  terms: {
    itemNoun: 'Wholesale SKU',
    categoryNoun: 'Category',
    orderNoun: 'B2B Tax Invoice',
    invoiceTitle: 'Commercial Tax Invoice',
    customerNoun: 'B2B Client / Dealer',
    fulfillmentNoun: 'Warehouse Dispatch',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 11. SERVICE CENTER & REPAIR WORKSHOP TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const SERVICE_CENTER_TEMPLATE: BusinessTemplate = {
  templateId: 'SERVICE_CENTER',
  name: 'Service Center & Repair Workshop',
  description: 'Engineered for device/auto repair jobs, tracking technician labor charges, spare parts usage, and Job Card repair status pipelines.',
  industryCategory: 'Services & Care',
  icon: 'Wrench',
  themeColor: '#0284C7',
  modules: {
    enableServicePoints: true,
    enableFulfillmentStations: true,
    enableBarcodeScanning: true,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: true,
    enableProductVariants: false,
    enableProductBOM: false,
    enableCustomerCreditLedger: true,
    enableLoyaltyProgram: false,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Service POS', path: '/billing', icon: 'ReceiptText', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Job Cards Queue', path: '/orders', icon: 'FileText', rolesAllowed: ['ADMIN', 'MANAGER', 'STAFF'] },
    { name: 'Service Bays', path: '/tables', icon: 'GripHorizontal', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Services & Parts', path: '/menu', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Spare Parts Stock', path: '/inventory', icon: 'Boxes', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Customers & Vehicles', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Labor & Repair Services', description: 'Diagnostic, servicing, screen replace and software flash' },
    { name: 'Replacement Spare Parts', description: 'Original batteries, filters, ICs and displays' },
    { name: 'Preventative Maintenance', description: 'General checkup, oil change and cleaning' },
  ],
  productFields: {
    inputMode: 'SERVICE_PICKER',
    visibleFields: ['name', 'categoryId', 'price', 'gst', 'hsnCode'],
    requiredFields: ['name', 'price'],
    customAttributes: [
      { key: 'serviceType', label: 'Item Type', type: 'SELECT', options: ['Labor Service', 'Spare Part', 'Consumable'], default: 'Labor Service', showInGrid: true },
      { key: 'estimatedMinutes', label: 'Estimated Repair Time (Mins)', type: 'NUMBER', default: 60 },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'address', 'deviceVehicleModel', 'serialImeiRegNo'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: true,
  },
  invoiceLayout: {
    defaultFormat: 'SERVICE_JOB_SHEET',
    headerTitle: 'ProCare Repair & Service Hub',
    tagline: 'Expert Diagnostics, Certified Technicians & Spares',
    taxLicenseLabel: 'GSTIN / Service Lic',
    visibleReceiptFields: ['deviceModel', 'serialImei', 'reportedFault', 'technicianNotes', 'sparePartsList', 'laborCharge', 'amountInWords', 'signatureLine'],
    termsText: '30 days warranty on replaced spare parts only. No warranty on water damage.',
    thankYouNote: 'Thank you for trusting ProCare Service Center!',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Service Revenue", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'openJobs', title: 'Open Job Cards in Workshop', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Service Billing Trend', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'REPAIR_JOB_INVOICE', name: 'Repair Job Sheet & Tax Invoice', requiresCustomer: true, requiresServicePoint: true, defaultPaymentMethod: 'UPI' },
    { code: 'PARTS_SALE', name: 'Over Counter Spare Part Sale', defaultPaymentMethod: 'CASH' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Service Invoices Register', defaultColumns: ['orderNumber', 'customerName', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'Service Tax (SAC) Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '9987',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Labor & Repair SAC 9987 (18%)', rate: 18.0, hsnPrefix: '9987' },
      { label: 'Spare Parts Goods (18%)', rate: 18.0, hsnPrefix: '8504' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'PENDING',
    allowSplitPayments: true,
    allowCreditSale: true,
    requireCustomerForInvoice: true,
    autoPrintOnCheckout: true,
    defaultEstimatedTimeMinutes: 120,
    orderStatusPipeline: [
      { code: 'PENDING', label: 'Job Received / Bay Assigned', color: 'orange', nextAllowedStatuses: ['PREPARING'] },
      { code: 'PREPARING', label: 'In Diagnostics & Repair', color: 'blue', nextAllowedStatuses: ['READY'] },
      { code: 'READY', label: 'Tested & Ready for Delivery', color: 'green', nextAllowedStatuses: ['COMPLETED'] },
      { code: 'COMPLETED', label: 'Delivered & Bill Settled', color: 'emerald', nextAllowedStatuses: [], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Customer Declined Repair', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'SVC/',
    orderPrefix: 'JOB-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: 'A4',
    activeTheme: 'DARK_SLATE',
  },
  terms: {
    itemNoun: 'Service / Part',
    categoryNoun: 'Service Department',
    orderNoun: 'Job Card',
    invoiceTitle: 'Service Job Sheet & Invoice',
    customerNoun: 'Client / Vehicle Owner',
    servicePointNoun: 'Service Bay',
    fulfillmentNoun: 'Workshop Bay',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 12. SALON & SPA WELLNESS TEMPLATE
// ─────────────────────────────────────────────────────────────────────────────
export const SALON_TEMPLATE: BusinessTemplate = {
  templateId: 'SALON',
  name: 'Salon & Luxury Spa',
  description: 'Designed for beauty salons and spas with Stylist Chair bookings, package memberships, appointment scheduling, and commission tracking.',
  industryCategory: 'Services & Care',
  icon: 'Scissors',
  themeColor: '#F43F5E',
  modules: {
    enableServicePoints: true,
    enableFulfillmentStations: false,
    enableBarcodeScanning: false,
    enableBatchExpiryTracking: false,
    enableSerialIMEI: false,
    enableProductVariants: false,
    enableProductBOM: false,
    enableCustomerCreditLedger: false,
    enableLoyaltyProgram: true,
    enablePromotionsEngine: true,
    enableInventory: true,
    enableCrm: true,
    enablePromotions: true,
    enableReports: true,
    enableStaffManagement: true,
  },
  menus: [
    { name: 'Dashboard', path: '/', icon: 'LayoutDashboard', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Salon POS', path: '/billing', icon: 'ReceiptText', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Stylist Chairs', path: '/tables', icon: 'GripHorizontal', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Services & Packages', path: '/menu', icon: 'BookOpen', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Cosmetics Stock', path: '/inventory', icon: 'Package', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Clients & Rewards', path: '/customers', icon: 'Users', rolesAllowed: ['ADMIN', 'MANAGER', 'CASHIER'] },
    { name: 'Promos & Offers', path: '/promotions', icon: 'Tag', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Reports', path: '/reports', icon: 'BarChart3', rolesAllowed: ['ADMIN', 'MANAGER'] },
    { name: 'Settings', path: '/settings', icon: 'Settings', rolesAllowed: ['ADMIN'] },
  ],
  categories: [
    { name: 'Hair Care & Styling', description: 'Haircut, coloring, keratin and spa' },
    { name: 'Skin & Facials', description: 'Gold facial, hydra facials and cleanup' },
    { name: 'Body Spa & Massages', description: 'Aromatherapy, deep tissue and scrubs' },
    { name: 'Manicure & Pedicure', description: 'Nail art, spa manicure and pedicure' },
    { name: 'Bridal & Grooming Packages', description: 'Complete head to toe makeover packages' },
  ],
  productFields: {
    inputMode: 'TOUCH_GRID',
    visibleFields: ['name', 'categoryId', 'price', 'gst', 'durationMinutes'],
    requiredFields: ['name', 'price'],
    customAttributes: [
      { key: 'durationMinutes', label: 'Service Duration (Mins)', type: 'NUMBER', default: 45, showInGrid: true },
      { key: 'genderTarget', label: 'Target Clientele', type: 'SELECT', options: ['Unisex', 'Female Only', 'Male Only', 'Kids'], default: 'Unisex', showInGrid: true },
    ],
  },
  customerFields: {
    visibleFields: ['name', 'mobile', 'birthday', 'anniversary', 'loyaltyPoints', 'membershipTier'],
    requiredFields: ['name', 'mobile'],
    allowCreditBilling: false,
  },
  invoiceLayout: {
    defaultFormat: '80MM_THERMAL',
    headerTitle: 'Aura Luxury Salon & Spa',
    tagline: 'Rejuvenate Your Beauty & Wellness',
    taxLicenseLabel: 'GSTIN / Trade Lic',
    visibleReceiptFields: ['chairNumber', 'stylistName', 'membershipDiscount', 'loyaltyPointsEarned', 'upiQr'],
    termsText: 'Appointments must be rescheduled at least 2 hours in advance.',
    thankYouNote: 'Thank you for pampering yourself at Aura Salon & Spa!',
    showQrCode: true,
    showLogo: true,
  },
  dashboardWidgets: [
    { id: 'todayRevenue', title: "Today's Salon Revenue", type: 'KPI_CARD', gridSpan: 1 },
    { id: 'activeChairs', title: 'Occupied Styling Chairs', type: 'KPI_CARD', gridSpan: 1 },
    { id: 'revenueTrend', title: 'Weekly Bookings Trend', type: 'BAR_CHART', gridSpan: 4 },
  ],
  invoiceTypes: [
    { code: 'SALON_BILL', name: 'Salon Service Bill', requiresServicePoint: true, defaultPaymentMethod: 'UPI' },
    { code: 'PRODUCT_PURCHASE', name: 'Cosmetic Product Sale', defaultPaymentMethod: 'CASH' },
  ],
  reports: [
    { id: 'BILLING_DETAILS', category: 'Sales & Revenue', name: 'Salon Billing Register', defaultColumns: ['orderNumber', 'customerName', 'total'] },
    { id: 'GST_REPORT', category: 'Compliance & Audit', name: 'Spa & Salon GST Summary', defaultColumns: ['hsnCode', 'taxableValue', 'cgst', 'sgst'] },
  ],
  taxRules: {
    taxSystemName: 'GST',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    cgstSgstSplit: true,
    defaultHsnCode: '9997',
    taxExemptAllowed: false,
    taxSlabs: [
      { label: 'Beauty & Wellness SAC 9997 (18%)', rate: 18.0, hsnPrefix: '9997' },
    ],
  },
  workflows: {
    defaultInitialStatus: 'COMPLETED',
    allowSplitPayments: true,
    allowCreditSale: false,
    requireCustomerForInvoice: false,
    autoPrintOnCheckout: true,
    orderStatusPipeline: [
      { code: 'COMPLETED', label: 'Service Finished & Paid', color: 'emerald', nextAllowedStatuses: ['CANCELLED'], autoDeductStock: true },
      { code: 'CANCELLED', label: 'Cancelled Appointment', color: 'red', nextAllowedStatuses: [] },
    ],
  },
  permissions: {
    ADMIN: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: true },
    CASHIER: { billingPos: true, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
    MANAGER: { billingPos: true, cancelOrders: true, manualDiscount: true, reports: true, manageMenu: true, manageInventory: true, settings: false },
    STAFF: { billingPos: false, cancelOrders: false, manualDiscount: false, reports: false, manageMenu: false, manageInventory: false, settings: false },
  },
  settingsDefaults: {
    currencySymbol: '₹',
    currencyCode: 'INR',
    defaultTaxRate: 18.0,
    taxCalculationMode: 'EXCLUSIVE',
    counterPrefix: 'SAL/',
    orderPrefix: 'ORD-',
    invoiceResetFrequency: 'YEARLY',
    defaultPaperSize: '80MM',
    activeTheme: 'DARK_GOLD',
  },
  terms: {
    itemNoun: 'Service Treatment',
    categoryNoun: 'Service Category',
    orderNoun: 'Salon Appointment Bill',
    invoiceTitle: 'Salon & Spa Receipt',
    customerNoun: 'Client',
    servicePointNoun: 'Styling Chair / Spa Suite',
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// REGISTRY DICTIONARY
// ─────────────────────────────────────────────────────────────────────────────
export const ALL_BUSINESS_TEMPLATES: Record<string, BusinessTemplate> = {
  RESTAURANT: RESTAURANT_TEMPLATE,
  RETAIL: RETAIL_TEMPLATE,
  SUPERMARKET: SUPERMARKET_TEMPLATE,
  MEDICAL: MEDICAL_TEMPLATE,
  BAKERY: BAKERY_TEMPLATE,
  ELECTRONICS: ELECTRONICS_TEMPLATE,
  HARDWARE: HARDWARE_TEMPLATE,
  GARMENTS: GARMENTS_TEMPLATE,
  JEWELLERY: JEWELLERY_TEMPLATE,
  WHOLESALE: WHOLESALE_TEMPLATE,
  SERVICE_CENTER: SERVICE_CENTER_TEMPLATE,
  SALON: SALON_TEMPLATE,
  CUSTOM: RESTAURANT_TEMPLATE,
};
